name: soundsense
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  noise_meter: ^5.0.2
  tflite_flutter: ^0.11.0
  audio_streamer: ^4.2.2
  http: ^1.2.1
  shared_preferences: ^2.2.2
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  record: ^6.0.0
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  
  
  # Your TTS feature
  flutter_tts: ^3.8.5
  
  # Friend's SOS & Location features
  geolocator: ^13.0.2
  url_launcher: ^6.2.4
  
  # Additional features
  flutter_local_notifications: ^17.0.0
  wakelock_plus: ^1.2.0
  torch_light: ^1.0.0
  flutter_dotenv: ^6.0.0
  picovoice_flutter: ^3.0.4
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
      - assets/models/
      - assets/animations/
      - assets/images/
      - .env